spring:
  datasource:
    name: health_system  #数据库名
    url: jdbc:mysql://localhost:3306/health_system #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: mapper/UserMapper.xml  #配置映射文件
  type-aliases-package: com.example.health_system.bean #配置实体类